version: "2"

services:
  jmaster:
    build:
      context: master/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - JAVA_OPTS
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size:  "200m"
        max-file: "3"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/jenkins-backup/jobs:/var/jenkins_home/jobs
      - $HOME/jenkins-backup/userContent:/var/jenkins_home/userContent
      - /etc/localtime:/etc/localtime
